IMPORTING LIBRARIES

In [93]:
import numpy as np
import threading 
import os
import time
import queue

QUESTION 1: MATRIX MULTIPLICATION

In [94]:
dim = 100
matrix_a = np.random.randint(1,1000,(dim,dim))
matrix_b = np.random.randint(1,1000,(dim,dim))

SERIAL OPERATION

In [79]:
%%time 
matrix_c = np.zeros((dim,dim))
matrix_c = matrix_c.astype(int)

for i in range(dim): 
    for j in range(dim): 
        for k in range(dim): 
            matrix_c[i][j] += matrix_a[i][k] * matrix_b[k][j] 

print(matrix_c)
print("Time for Serial Operation: ")

[[23248954 24249236 24621101 ... 22035152 25215739 22471418]
 [25511150 26041081 23860856 ... 24151654 25477295 23405033]
 [27903354 29582936 29287209 ... 26553738 28628214 27857332]
 ...
 [26968861 28618393 28315070 ... 27922893 28193321 26198859]
 [26677553 26910670 26741521 ... 25581455 27489760 25725278]
 [25654807 27485044 26770785 ... 25464290 27054688 25839348]]

CPU times: user 1.48 s, sys: 1.04 ms, total: 1.48 s
Wall time: 1.49 s


MULTITHREADING

In [80]:
%%time
n=matrix_a.shape[0]

def work_1(matrix_a, matrix_b, matrix_c, i):
    for j in range(n):
        for k in range(n):
            matrix_c[i][j] += matrix_a[i][k] * matrix_b[k][j]
            

threads = [None]*n
matrix_c = np.zeros((n,n))

for i in range(n):
  threads[i] = threading.Thread(target = work_1, args = (matrix_a, matrix_b, matrix_c, i))
  threads[i].start()

for i in range(n):
  threads[i].join()

print(matrix_c)
print("Time for Multithreading: ")

[[23248954. 24249236. 24621101. ... 22035152. 25215739. 22471418.]
 [25511150. 26041081. 23860856. ... 24151654. 25477295. 23405033.]
 [27903354. 29582936. 29287209. ... 26553738. 28628214. 27857332.]
 ...
 [26968861. 28618393. 28315070. ... 27922893. 28193321. 26198859.]
 [26677553. 26910670. 26741521. ... 25581455. 27489760. 25725278.]
 [25654807. 27485044. 26770785. ... 25464290. 27054688. 25839348.]]

CPU times: user 1.45 s, sys: 15.6 ms, total: 1.46 s
Wall time: 1.51 s


USING NUMPY

In [81]:
%%time

matix_c = np.dot(matrix_a,matrix_b)
print(matrix_c)
print()

[[23248954. 24249236. 24621101. ... 22035152. 25215739. 22471418.]
 [25511150. 26041081. 23860856. ... 24151654. 25477295. 23405033.]
 [27903354. 29582936. 29287209. ... 26553738. 28628214. 27857332.]
 ...
 [26968861. 28618393. 28315070. ... 27922893. 28193321. 26198859.]
 [26677553. 26910670. 26741521. ... 25581455. 27489760. 25725278.]
 [25654807. 27485044. 26770785. ... 25464290. 27054688. 25839348.]]

CPU times: user 3.56 ms, sys: 18 µs, total: 3.57 ms
Wall time: 4.13 ms


ANALYZING:

QUESTION 2: Linear Search

In [82]:
lst = np.random.randint(500,size = 5000000)

LINEAR SEARCH

In [83]:
%%time 
X = 499
found_lst = []
for i in range(len(lst)):
    if(X == lst[i]):
        found_lst.append(i)
print(found_lst)
print("Time for Serial Operation: ")

[53, 1620, 1622, 2460, 2571, 2620, 4537, 4617, 5236, 5271, 5839, 6033, 6253, 6327, 6408, 6693, 6766, 7849, 8394, 8581, 9094, 9113, 9849, 10084, 10270, 10281, 10667, 10975, 11033, 11996, 12783, 13114, 14114, 14337, 15367, 15985, 16862, 17123, 17591, 17704, 18010, 19325, 19993, 20459, 21210, 21862, 22073, 22356, 22639, 23455, 23744, 24026, 25027, 27636, 27756, 28126, 28339, 28450, 28753, 28936, 28993, 29656, 29751, 30419, 30693, 30727, 31152, 31527, 32532, 32591, 32633, 32847, 33768, 34206, 35099, 35790, 36151, 36728, 36729, 37207, 37448, 37743, 38338, 38884, 39488, 39541, 40260, 40344, 40571, 41226, 41945, 43015, 43337, 43570, 44235, 44296, 46153, 46261, 46295, 46854, 47472, 47888, 48503, 48702, 48950, 49129, 49199, 49473, 49656, 50030, 50613, 50620, 50804, 51220, 51284, 51981, 52150, 52340, 52737, 52738, 52941, 52942, 52962, 52993, 53488, 53748, 53874, 55532, 55680, 56174, 56307, 56702, 56794, 57741, 57747, 58086, 58205, 58649, 58742, 58798, 59333, 59727, 59931, 60310, 61302, 62438, 62

MULTITHREADING

In [84]:
%%time

n=len(lst)
def linear_1(lst, check):
    res_t = []
    for i in range(len(lst)):
        if(check == lst[i]):
            res_t.append(i)
    print(res_t)
def linear_2(lst, check):
    res_t = []
    for i in range(len(lst)):
        if(check == lst[i]):
            res_t.append((n//2)+i)
    print(res_t)

check = 499
threads = [None]*2

threads[0] = threading.Thread(target = linear_1, args = (lst[:(n//2)], check))
threads[0].start()
threads[1] = threading.Thread(target = linear_2, args = (lst[(n//2):], check))
threads[1].start()

for i in range(2):
  threads[i].join()
print("Time for Multithreading: ")

[53, 1620, 1622, 2460, 2571, 2620, 4537, 4617, 5236, 5271, 5839, 6033, 6253, 6327, 6408, 6693, 6766, 7849, 8394, 8581, 9094, 9113, 9849, 10084, 10270, 10281, 10667, 10975, 11033, 11996, 12783, 13114, 14114, 14337, 15367, 15985, 16862, 17123, 17591, 17704, 18010, 19325, 19993, 20459, 21210, 21862, 22073, 22356, 22639, 23455, 23744, 24026, 25027, 27636, 27756, 28126, 28339, 28450, 28753, 28936, 28993, 29656, 29751, 30419, 30693, 30727, 31152, 31527, 32532, 32591, 32633, 32847, 33768, 34206, 35099, 35790, 36151, 36728, 36729, 37207, 37448, 37743, 38338, 38884, 39488, 39541, 40260, 40344, 40571, 41226, 41945, 43015, 43337, 43570, 44235, 44296, 46153, 46261, 46295, 46854, 47472, 47888, 48503, 48702, 48950, 49129, 49199, 49473, 49656, 50030, 50613, 50620, 50804, 51220, 51284, 51981, 52150, 52340, 52737, 52738, 52941, 52942, 52962, 52993, 53488, 53748, 53874, 55532, 55680, 56174, 56307, 56702, 56794, 57741, 57747, 58086, 58205, 58649, 58742, 58798, 59333, 59727, 59931, 60310, 61302, 62438, 62

BUILT IN FUNCTION

In [85]:
%%time
found_lst = np.where(lst == 499)
print(found_lst)
print()

(array([     53,    1620,    1622, ..., 4999003, 4999698, 4999721]),)

CPU times: user 11.6 ms, sys: 3.99 ms, total: 15.6 ms
Wall time: 16.4 ms


QUESTION 3: Array Sum

In [86]:
lst = np.random.randint(500,size = 5000000)

USING LOOP

In [87]:
%%time
sum = 0
for i in range(len(lst)):
    sum += lst[i]
print(sum)
print("Time for Serial Operation: ")

1247685582

CPU times: user 1.52 s, sys: 1.04 ms, total: 1.52 s
Wall time: 1.52 s


MULTITHREADING

In [88]:
%%time

def arr_sum(lst):
    sum = 0
    for i in range(len(lst)):
        sum += lst[i]
    return sum

que = queue.Queue()
threads_list = list()

n=len(lst)
total_sum = 0

t = threading.Thread(target=lambda q, arg1: q.put(arr_sum(arg1)), args=(que, lst[:(n//2)]))
t.start()
threads_list.append(t)

t2 = threading.Thread(target=lambda q, arg1: q.put(arr_sum(arg1)), args=(que, lst[(n//2):]))
t2.start()
threads_list.append(t2)

for t in threads_list:
    t.join()

while not que.empty():
    total_sum += que.get()
print(total_sum)
print("Time for Multithreading: ")

1247685582
CPU times: user 1.21 s, sys: 5.07 ms, total: 1.22 s
Wall time: 1.23 s


BUILT IN FUNCTION

In [89]:
%%time
lst.sum()

CPU times: user 6.52 ms, sys: 0 ns, total: 6.52 ms
Wall time: 9.23 ms


1247685582

QUESTION 4: Prime Numbers

In [90]:
start = 1
end = 50000

SERIAL OPERATION

In [91]:
%%time
lst=[]
for num in range(start, end + 1):
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           lst.append(num)
print(lst)
print("Time for Serial Operation: ")

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217,

MULTITHREADING

In [92]:
%%time

def prime(low,high,out):
    res=[]
    for num in range(low, high + 1):
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           res.append(num)
    out.put(res)

que = queue.Queue()
threads_list = list()

total = []

t1 = threading.Thread(prime(start, end//2, que))
t1.start()
threads_list.append(t1)

t2 = threading.Thread(prime(start//2, end, que))
t2.start()
threads_list.append(t2)

for t in threads_list:
    t.join()

for i in que.queue:
    total +=i
print(total)
print("Time for Multithreading: ")

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217,

ANALYZING

In [95]:
import time
import numpy as np

def using_loops():
    start_time = time.time()

    n = int(input("Enter dimension "))

    A = np.random.random((n,n))
    A = A * 10
    A = A.astype(int)

    B = np.random.random((n,n))
    B = B * 10
    B = B.astype(int)

    ans = np.zeros((n,n))
    ans = ans.astype(int)

    for i in range(n):
        for j in range(n): 
            for k in range(n): 
                ans[i][j] += A[i][k] * B[k][j] 

    end_time = time.time()        

    print()
    print("Time taken to multiply two matrices in series comes out to be : " + str(end_time - start_time))
from threading import Thread
import random
import math
import numpy as np
import threading
import time

Matrix_A = []
Matrix_B = []
Matrix_C = []

size_of_vectors_n = [int(math.pow(10,2)),int(math.pow(10,3)),int(math.pow(10,4))]

dimension_N = 2 # Default to a 2x2 matrix

num_of_threads = 1
def Input_for_matrix_dimensions():
    global dimension_N
    global num_of_threads
    
    dimension_N = int(input("Enter the number N to generate NxN matrix : "))
    num_of_threads = int(input("Enter the number of threads : "))
    
def Initialize_Matrix():
    global Matrix_A
    global Matrix_B
    global Matrix_C

    Matrix_A = np.random.random((dimension_N,dimension_N))
    Matrix_A = Matrix_A * 10
    Matrix_A = Matrix_A.astype(int)
    
    Matrix_B = np.random.random((dimension_N,dimension_N))
    Matrix_B = Matrix_B * 10
    Matrix_B = Matrix_B.astype(int)
    
    Matrix_C = np.zeros((dimension_N,dimension_N))
    Matrix_C = Matrix_C.astype(int)

def Matrix_multiply_parallel(start,end):
    for i in range(start,end):
        for j in range(dimension_N):
            for k in range(dimension_N):
                Matrix_C[i][j] += int(Matrix_A[i][k] * Matrix_B[k][j])
    
def Thread_function():
    start_time = time.time()
    global num_of_threads
    thread_handle = []

    for j in range(0,num_of_threads):
        t = Thread(target = Matrix_multiply_parallel, args=(int((dimension_N/num_of_threads) * j),int((dimension_N/num_of_threads) * (j+1))))
        thread_handle.append(t)
        t.start()   
        
    for j in range(0,num_of_threads):
        thread_handle[j].join()
    
    end_time = time.time()
    print("Time taken to multiply two matrices in parallel comes out to be : " + str(end_time - start_time))
import numpy as np
import time

def using_numpy():
    start_time = time.time()

    n = int(input("Enter dimension "))

    A = np.random.random((n,n))
    A = A * 10
    A = A.astype(int)

    B = np.random.random((n,n))
    B = B * 10
    B = B.astype(int)

    ans = np.dot(A,B)

    end_time = time.time()

    print("Time taken to multiply two matrices using numpy comes out to be : " + str(end_time - start_time))
    

Analyzing: ( Dimension 5,6,7,8,9 ) Number_of_threads = 2

In [99]:
for i in range(5):
    using_loops()
    
    Input_for_matrix_dimensions()
    Initialize_Matrix()
    Thread_function()
    
    using_numpy()
    print()
    print()
    

Enter dimension 5

Time taken to multiply two matrices in series comes out to be : 1.384214162826538
Enter the number N to generate NxN matrix : 5
Enter the number of threads : 2
Time taken to multiply two matrices in parallel comes out to be : 0.0007274150848388672
Enter dimension 5
Time taken to multiply two matrices using numpy comes out to be : 1.8348383903503418


Enter dimension 6

Time taken to multiply two matrices in series comes out to be : 2.303773880004883
Enter the number N to generate NxN matrix : 6
Enter the number of threads : 2
Time taken to multiply two matrices in parallel comes out to be : 0.0011358261108398438
Enter dimension 6
Time taken to multiply two matrices using numpy comes out to be : 1.8260939121246338


Enter dimension 7

Time taken to multiply two matrices in series comes out to be : 3.336845636367798
Enter the number N to generate NxN matrix : 7
Enter the number of threads : 2
Time taken to multiply two matrices in parallel comes out to be : 0.001057624

#### So it can be inferred from the above results that parallel computing with number of threads = 2 takes the least time in all the 5 cases. 
##### However using numpy library takes more time for lower dimesnsion arrays as compared to series computing but the time difference becomes largely diffrentiable in the favour of using numpy library once the dimension size increases.

Analyzing Number_of_threads = (1,2,3,4,5) , Dimenion  = 8

In [100]:
for i in range(5):
    
    Input_for_matrix_dimensions()
    Initialize_Matrix()
    Thread_function()

    print()

Enter the number N to generate NxN matrix : 8
Enter the number of threads : 1
Time taken to multiply two matrices in parallel comes out to be : 0.0013098716735839844

Enter the number N to generate NxN matrix : 8
Enter the number of threads : 2
Time taken to multiply two matrices in parallel comes out to be : 0.0017728805541992188

Enter the number N to generate NxN matrix : 8
Enter the number of threads : 3
Time taken to multiply two matrices in parallel comes out to be : 0.001413106918334961

Enter the number N to generate NxN matrix : 8
Enter the number of threads : 4
Time taken to multiply two matrices in parallel comes out to be : 0.002068758010864258

Enter the number N to generate NxN matrix : 8
Enter the number of threads : 5
Time taken to multiply two matrices in parallel comes out to be : 0.002011537551879883



So it can be clearly inferred that on INCREASING the number of threads the time for matrix multiplication INCREASES. This was evident as on increasing the number of threads the need for CPU resources increases